# -*- coding: utf-8 -*-
"""linearReggression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmx8cfnqdNIqOcdXpCGCF6H3mN1OHXCb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
data = pd.read_csv("/content/winemag-data-130k-v2.csv")


data = data[['points', 'price']].dropna()


X = data[['points']]
y = data['price']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


errors = y_test.values - y_pred
mse_manual = np.mean(errors ** 2)
print(f"Mathematical Mean Squared Error (MSE): {mse_manual:.2f}")
plt.figure(figsize=(8,6))
plt.scatter(X_test, y_test, color='lightblue', label='Actual Prices', alpha=0.6)
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Regression Line')

plt.title("Wine Price vs Points (Linear Regression)")
plt.xlabel("Wine Rating Points")
plt.ylabel("Wine Price (USD)")
plt.legend()
plt.grid(True)
plt.show()

